BACKGROUND_COLOR = (60, 156, 54)
WINDOW_HEIGHT = 600
WINDOW_WIDTH = 1000
NUM_OF_ROWS = 25
NUM_OF_COLS = 50

NUM_OF_BOOMS = 20
COLOR_TO_IGNOR = ()
FLAGֹֹֹֹ_HEIGHT = ?
FLAG_WIDTH
WINNER_SOUND =
LOSSER_SOUND =
SOLIGER_IMAGE =
TREE_IMAGE =
